/*-
 * CNIC demo USER_CTRL register map (user BAR).
 * Source: cnic_register_map.xlsx, tab USER_CTRL, cnic_demo_v0.2.0-rc0.
 */

#ifndef CNIC_USER_CTRL_REGS_H
#define CNIC_USER_CTRL_REGS_H

#ifndef QDMA_USER_CTRL_MAP
#define QDMA_USER_CTRL_MAP QDMA_USER_CTRL_MAP_CNIC
#endif

#define QDMA_USER_CTRL_MAP_CNIC   1
#define QDMA_USER_CTRL_MAP_XILINX 2

#if QDMA_USER_CTRL_MAP == QDMA_USER_CTRL_MAP_CNIC
#define QDMA_USER_CTRL_ST_IP_LOOPBACK 1
#else
#define QDMA_USER_CTRL_ST_IP_LOOPBACK 0
#endif

/* USER_CTRL block size within user BAR (Assembly tab). */
#define QDMA_USER_CTRL_BLOCK_SIZE        0x1000
#define QDMA_USER_CTRL_BLOCK_AXI_BASE    0x10000

/* Register offsets within USER_CTRL. */
#define QDMA_USER_CTRL_C2H_TRANSFER_LENGTH_OFF   0x04
#define QDMA_USER_CTRL_C2H_CONTROL_OFF           0x08
#define QDMA_USER_CTRL_C2H_WB_DATA_0_OFF         0x30
#define QDMA_USER_CTRL_C2H_WB_DATA_1_OFF         0x34
#define QDMA_USER_CTRL_C2H_WB_DATA_2_OFF         0x38
#define QDMA_USER_CTRL_C2H_WB_DATA_3_OFF         0x3C
#define QDMA_USER_CTRL_C2H_WB_DATA_4_OFF         0x40
#define QDMA_USER_CTRL_C2H_WB_DATA_5_OFF         0x44
#define QDMA_USER_CTRL_C2H_WB_DATA_6_OFF         0x48
#define QDMA_USER_CTRL_C2H_WB_DATA_7_OFF         0x4C
#define QDMA_USER_CTRL_C2H_WB_TYPE_OFF           0x50
#define QDMA_USER_CTRL_SCRATCH_REG_0_OFF         0x60
#define QDMA_USER_CTRL_SCRATCH_REG_1_OFF         0x64
#define QDMA_USER_CTRL_SCRATCH_REG_0_DEFAULT     0x02605061U

#define QDMA_USER_CTRL_QID_START_ADDR_PF0_OFF      0x70
#define QDMA_USER_CTRL_QID_START_ADDR_VF0_OFF      0x74
#define QDMA_USER_CTRL_QID_START_ADDR_VF1_OFF      0x78
#define QDMA_USER_CTRL_QID_START_ADDR_VF2_OFF      0x7C
#define QDMA_USER_CTRL_QID_START_ADDR_VF3_OFF      0x80
#define QDMA_USER_CTRL_QID_START_ADDR_VF4_OFF      0x84
#define QDMA_USER_CTRL_QID_START_ADDR_VF5_OFF      0x88
#define QDMA_USER_CTRL_QID_START_ADDR_VF6_OFF      0x8C
#define QDMA_USER_CTRL_QID_START_ADDR_VF7_OFF      0x90
#define QDMA_USER_CTRL_QID_START_ADDR_VF8_OFF      0x94
#define QDMA_USER_CTRL_QID_START_ADDR_VF9_OFF      0x98
#define QDMA_USER_CTRL_QID_START_ADDR_VF10_OFF     0x9C
#define QDMA_USER_CTRL_QID_START_ADDR_VF11_OFF     0xA0
#define QDMA_USER_CTRL_QID_START_ADDR_VF12_OFF     0xA4
#define QDMA_USER_CTRL_QID_START_ADDR_VF13_OFF     0xA8
#define QDMA_USER_CTRL_QID_START_ADDR_VF14_OFF     0xAC
#define QDMA_USER_CTRL_QID_START_ADDR_VF15_OFF     0xBC

#define QDMA_USER_CTRL_QID_END_ADDR_PF0_OFF        0x170
#define QDMA_USER_CTRL_QID_END_ADDR_VF0_OFF        0x174
#define QDMA_USER_CTRL_QID_END_ADDR_VF1_OFF        0x178
#define QDMA_USER_CTRL_QID_END_ADDR_VF2_OFF        0x17C
#define QDMA_USER_CTRL_QID_END_ADDR_VF3_OFF        0x180
#define QDMA_USER_CTRL_QID_END_ADDR_VF4_OFF        0x184
#define QDMA_USER_CTRL_QID_END_ADDR_VF5_OFF        0x188
#define QDMA_USER_CTRL_QID_END_ADDR_VF6_OFF        0x18C
#define QDMA_USER_CTRL_QID_END_ADDR_VF7_OFF        0x190
#define QDMA_USER_CTRL_QID_END_ADDR_VF8_OFF        0x194
#define QDMA_USER_CTRL_QID_END_ADDR_VF9_OFF        0x198
#define QDMA_USER_CTRL_QID_END_ADDR_VF10_OFF       0x19C
#define QDMA_USER_CTRL_QID_END_ADDR_VF11_OFF       0x1A0
#define QDMA_USER_CTRL_QID_END_ADDR_VF12_OFF       0x1A4
#define QDMA_USER_CTRL_QID_END_ADDR_VF13_OFF       0x1A8
#define QDMA_USER_CTRL_QID_END_ADDR_VF14_OFF       0x1AC
#define QDMA_USER_CTRL_QID_END_ADDR_VF15_OFF       0x1BC

#define QDMA_USER_CTRL_PKT_CNT_PF0_OFF             0x200
#define QDMA_USER_CTRL_PKT_CNT_VF0_OFF             0x204
#define QDMA_USER_CTRL_PKT_CNT_VF1_OFF             0x208
#define QDMA_USER_CTRL_PKT_CNT_VF2_OFF             0x20C
#define QDMA_USER_CTRL_PKT_CNT_VF3_OFF             0x210
#define QDMA_USER_CTRL_PKT_CNT_VF4_OFF             0x214
#define QDMA_USER_CTRL_PKT_CNT_VF5_OFF             0x218
#define QDMA_USER_CTRL_PKT_CNT_VF6_OFF             0x21C
#define QDMA_USER_CTRL_PKT_CNT_VF7_OFF             0x220
#define QDMA_USER_CTRL_PKT_CNT_VF8_OFF             0x224
#define QDMA_USER_CTRL_PKT_CNT_VF9_OFF             0x228
#define QDMA_USER_CTRL_PKT_CNT_VF10_OFF            0x22C
#define QDMA_USER_CTRL_PKT_CNT_VF11_OFF            0x230
#define QDMA_USER_CTRL_PKT_CNT_VF12_OFF            0x234
#define QDMA_USER_CTRL_PKT_CNT_VF13_OFF            0x238
#define QDMA_USER_CTRL_PKT_CNT_VF14_OFF            0x23C
#define QDMA_USER_CTRL_PKT_CNT_VF15_OFF            0x240

#define QDMA_USER_CTRL_BYTE_CNT_PF0_OFF            0x300
#define QDMA_USER_CTRL_BYTE_CNT_VF0_OFF            0x304
#define QDMA_USER_CTRL_BYTE_CNT_VF1_OFF            0x308
#define QDMA_USER_CTRL_BYTE_CNT_VF2_OFF            0x30C
#define QDMA_USER_CTRL_BYTE_CNT_VF3_OFF            0x310
#define QDMA_USER_CTRL_BYTE_CNT_VF4_OFF            0x314
#define QDMA_USER_CTRL_BYTE_CNT_VF5_OFF            0x318
#define QDMA_USER_CTRL_BYTE_CNT_VF6_OFF            0x31C
#define QDMA_USER_CTRL_BYTE_CNT_VF7_OFF            0x324
#define QDMA_USER_CTRL_BYTE_CNT_VF8_OFF            0x328
#define QDMA_USER_CTRL_BYTE_CNT_VF9_OFF            0x32C
#define QDMA_USER_CTRL_BYTE_CNT_VF10_OFF           0x330
#define QDMA_USER_CTRL_BYTE_CNT_VF11_OFF           0x334
#define QDMA_USER_CTRL_BYTE_CNT_VF12_OFF           0x338
#define QDMA_USER_CTRL_BYTE_CNT_VF13_OFF           0x33C
#define QDMA_USER_CTRL_BYTE_CNT_VF14_OFF           0x340
#define QDMA_USER_CTRL_BYTE_CNT_VF15_OFF           0x344

/* c2h_control @ 0x08 */
#define QDMA_USER_CTRL_C2H_CLEAR_MARKER_PKT          (1U << 0)
#define QDMA_USER_CTRL_C2H_GEN_USER_RESET_N        (1U << 1)

#define QDMA_USER_CTRL_C2H_TRANSFER_LENGTH_DEFAULT   0x80U
#define QDMA_USER_CTRL_C2H_TRANSFER_LENGTH_MASK      0xFFFFU

#ifndef RX_TX_MAX_RETRY
#define RX_TX_MAX_RETRY  1500
#endif

/* CNIC ST IP loopback: poll until this many bytes or retries exhausted. */
#define QDMA_CNIC_ST_LOOPBACK_RX_RETRIES   (RX_TX_MAX_RETRY * 500)
#define QDMA_CNIC_ST_LOOPBACK_RX_DELAY_US  10

#if QDMA_USER_CTRL_MAP == QDMA_USER_CTRL_MAP_CNIC
/* CNIC names used by testapp (no Xilinx example registers at 0x0/0x20). */
#define C2H_ST_LEN_REG              QDMA_USER_CTRL_C2H_TRANSFER_LENGTH_OFF
#define C2H_CONTROL_REG             QDMA_USER_CTRL_C2H_CONTROL_OFF
#define ST_LOOPBACK_EN              0x1
#else
/* Xilinx example-design user BAR map. */
#define C2H_ST_QID_REG              0x0
#define C2H_ST_LEN_REG              0x4
#define C2H_CONTROL_REG             0x8
#define ST_LOOPBACK_EN              0x1
#define ST_C2H_START_VAL            0x2
#define ST_C2H_IMMEDIATE_DATA_EN    0x4
#define C2H_CONTROL_REG_MASK        0xF
#define H2C_CONTROL_REG             0xC
#define H2C_STATUS_REG              0x10
#define C2H_PACKET_COUNT_REG        0x20
#define C2H_STATUS_REG              0x18
#define C2H_STREAM_MARKER_PKT_GEN_VAL  0x22
#define MARKER_RESPONSE_COMPLETION_BIT 0x1
#endif

#endif /* CNIC_USER_CTRL_REGS_H */
